# Generated by Django 2.1.7 on 2019-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binatang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='images')),
                ('nama', models.CharField(max_length=255)),
                ('latin', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
            ],
        ),
    ]
